stages:
  data_ingestion:
    cmd: python -m src.ShortTermForecast.pipeline.stage_00_data_ingestion
    wdir: .
    deps:
      - src/ShortTermForecast/pipeline/stage_00_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/

  time_series_cv:
    cmd: python -m src.ShortTermForecast.pipeline.stage_01_time_series_cv
    wdir: .
    deps:
      - src/ShortTermForecast/pipeline/stage_01_time_series_cv.py
      - config/config.yaml
      - artifacts/data_ingestion/
    outs:
      - artifacts/cross_validation/
